name: Integration
on: [ 'push' ]
jobs:
    nuxt:
        name: Nuxt
        runs-on: ubuntu-latest
        steps:
            -   name: Set up repository
                uses: actions/checkout@v3
            -   name: Set up node
                uses: actions/setup-node@v1
                with:
                    node-version: 16
            -   name: Cache node_modules
                uses: actions/cache@v2
                with:
                    path: '**/node_modules'
                    key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
            -   name: Install npm dependencies
                if: steps.npm-cache.outputs.cache-hit != 'true'
                run: npm install
            -   name: Run build
                run: npm run build
            -   name: Create package
                run: |
                    cp package.json lib
                    npm pack
            -   name: Create nuxt app
                run: npx nuxi init inkline-nuxt
            -   name: Initialize inkline
                run: |
                    cd inkline-nuxt
                    npx inkline@latest init
            -   name: Install package
                run: |
                    cd inkline-nuxt
                    npm install ../inkline-*.tgz
            -   name: Build app
                run: |
                    cd inkline-nuxt
                    npm run build



